---
services:

  prometheus-init:
    image: busybox
    command: ["sh", "-c", "chown -R 65534:65534 /prometheus/data"]
    volumes:
      - data-prometheus:/prometheus/data

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 512m
    depends_on:
      prometheus-init:
        condition: service_completed_successfully
    environment:
      TZ: UTC
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --storage.tsdb.retention.time=90d
    user: "65534"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - data-prometheus:/prometheus/data
    ports:
      - "9090/tcp"

volumes:
  data-prometheus: {}
